# Generated by Django 5.0.7 on 2025-09-05 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back']},
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateField(blank=True, help_text='Введите конец срока статуса', null=True, verbose_name='Дата окончания статуса'),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Введите дату рождения', null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, help_text='Введите фото автора', null=True, upload_to='images', verbose_name='Фото автора'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(help_text='Выберите автора', to='catalog.author', verbose_name='Автор книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(help_text='Введите избражение обложки', upload_to='images', verbose_name='Изображение обложки'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.CharField(help_text='Введите год издания книги', max_length=4, verbose_name='Год издания'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='inv_nom',
            field=models.CharField(help_text='Введите инвентарный номер экземпляра', max_length=20, null=True, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.ForeignKey(help_text='Изменить состояние экземляра', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.status', verbose_name='Статус экземляра книги'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(help_text='Введитье статус экземпляра книги', max_length=20, verbose_name='Статус экземпляра книги'),
        ),
    ]
